BookAppCore/Models/Book.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Threading.Tasks;

namespace BookAppCore.Models
{
    public class Book
    {
        public int Id { get; set; }
        [Required(ErrorMessage ="Please enter a title name")]
        public string Title  { get; set; }
        [Required(ErrorMessage = "Please enter a year date")]
        
        public int Year { get; set; }
        [Required(ErrorMessage = "Please enter a price")]
        [DataType(DataType.Currency)]
        public decimal Price { get; set; }
        [Required(ErrorMessage = "Please enter a genre name")]
        public string Genre { get; set; }
        
        public string Publiser { get; set; }

        [Required(ErrorMessage = "Please enter an Author Id")]
        public int? AuthorID { get; set; }
        public virtual Author Author { get; set; }

        public virtual ICollection<Review> Reviews { get; set; }
    }

    public class Review
    {
        public int Id { get; set; }
        public string UserName { get; set; }
        public string Body { get; set; }
        public int Rating { get; set; }


        public int BookId { get; set; }
        public Book Book { get; set; }
    }
}

BookAppCore/Controllers/BooksController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using BookAppCore.Abstract;
using Microsoft.EntityFrameworkCore;
using Microsoft.AspNetCore.Mvc.Rendering;
using BookAppCore.Models;

// For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860

namespace BookAppCore.Controllers
{
    public class BooksController : Controller
    {
        private IBookRepository repo;

        public BooksController(IBookRepository _repo) { repo = _repo; }


        public IActionResult Index()
        {
            var q =  repo.Books;

            return View(q);
        }

        public IActionResult Edit(int id)
        {
            ViewBag.Genre = new SelectList(repo.Books.Select(p => p.Genre).Distinct());

            return View(repo.Books.FirstOrDefault(b => b.Id == id));
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Edit(Book book)
        {
            if (ModelState.IsValid)
            {
                repo.SaveMovie(book);
                TempData["message"] = $"{book.Title} has been saved";
                return  RedirectToAction("Index");
            } else
            {
                return View(book);
            }
        }

        public ViewResult Create()
        {
            return View("Edit", new Book());
        }


        [HttpPost]
        public IActionResult Delete(int id)
        {
            var book = repo.DeleteMovie(id);
            if(book != null)
            {
                ViewBag.Message = $"{book.Title} has beed deleted";

                
            }

           return RedirectToAction("Index");
        }

        
    }
}

BookAppCore/Controllers/ReviewsController.cs
using Microsoft.AspNetCore.Mvc;
using BookAppCore.Abstract;
using System.Collections.Generic;
using System.Linq;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using BookAppCore.Models;


// For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860

namespace BookAppCore.Controllers
{
    public class ReviewsController : Controller
    {
        private BookDbContext context;
        private IBookRepository repo;
        private IReviewRepository Rrepo;

        public ReviewsController(IBookRepository _repo, IReviewRepository _Rrepo, BookDbContext _context)
        {
            repo = _repo;
            Rrepo = _Rrepo;
            context = _context;
        }

        public IActionResult Index([Bind(Prefix ="id")]int Bookid)
        {

            var review = repo.Books.Include(r => r.Reviews).SingleOrDefault(d => d.Id == Bookid);
                
            if(review == null)
            {
                return NotFound();
                
            }

            return View(review);
        }

        [HttpGet]
        public IActionResult Edit(int Bookid)
        {
            
            var q = context.Reviews.Find(Bookid);
            return View(q);
        }


        [HttpPost]
        public IActionResult Edit(Review review)
        {
            if (ModelState.IsValid)
            {
                // context.Reviews.Add(review);
                context.Entry(review).State = EntityState.Modified;
                context.SaveChanges();
                return RedirectToAction("Index", new { id = review.BookId });
            }
           
                return View(review);
            
        }



        public IActionResult Create(int BookId)
        {
            return View();
        }


        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Create(Review view)
        {
            if (ModelState.IsValid)
            {
                context.Reviews.Add(view);
                context.SaveChanges();
                return RedirectToAction("Index", new { id = view.BookId });
            }
            return View(view);
        }

        protected override void Dispose(bool disposing)
        {
            context.Dispose();
            base.Dispose(disposing);
        }

    }
}

BookAppCore/Views/Books/Edit.cshtml
@model Book

    <div class="container">
        <div class="jumbotron">
           <h2 class="text-center"> Create or Update Books</h2>

        </div>
        <form asp-action="Edit" method="post">
            <input type="hidden" asp-for="Id" />
            <div asp-validation-summary="All"></div>

            <div class="form-group">
                <label asp-for="Title">Title</label>
                <div><span asp-validation-for="Title" class="text-danger"></span></div>
                <input class="form-control" asp-for="Title  "/>
                
            </div>
            <div class="form-group">
                <label asp-for="Genre"></label>
                <div><span asp-validation-for="Genre" class="text-danger"></span></div>
                <input class="form-control" asp-for="Genre" />
                
            </div>
            <div class="form-group">
                <label asp-for="Year"></label>
                <div><span asp-validation-for="Year" class="text-danger"></span></div>
                <input class="form-control" asp-for="Year" />
                
            </div>
            <div class="form-group">
                
                <div class="form-group">
                    <label class="sr-only" asp-for="Price">Price (in dollars)</label>
                    <div class="input-group">
                        <div class="input-group-addon">$</div>
                        <div><span asp-validation-for="Price" class="text-danger"></span></div>
                        <input asp-for="Price" class="form-control"  placeholder="Price">
                        <div class="input-group-addon">.00</div>
                        
                    </div>
                </div>
                </div>
                @*<div class="form-group">
                    <label asp-for="Price"></label>
                    <input class="form-control" asp-for="Price" />
                    <span asp-validation-for="Price"></span>
                </div>*@

                <div class="form-group">
                    <label asp-for="Publiser"></label>
                    <div><span asp-validation-for="Publiser" class="text-danger"></span></div>
                    <input class="form-control" asp-for="Publiser" />
                    
                </div>
                <div class="form-group">
                    <label asp-for="AuthorID">Author Id</label>
                    <div><span asp-validation-for="AuthorID" class="text-danger"></span></div>
                    <input class="form-control" asp-for="AuthorID" />
                    
                </div>

                <button type="submit" class="btn btn-primary">Save Info</button>
                <a asp-action="Index" class="btn btn-default" asp-controller="Books">Cancel</a>
</form>
    </div>

BookAppCore/Views/Books/Index.cshtml
@model IEnumerable<Book>

<div class="container">
    <div class="jumbotron">
        <h2 class="text-center">List of Books</h2>
        @if (TempData["message"] != null)
        {
            <div class="alert alert-success">@TempData["message"]</div>

        }
    </div>
    <a asp-action="Create" class="btn btn-primary">Create New Book</a>
    <table class="table table-sm table-responsive table-bordered">
        <tr>
            <th>Id</th>
            <th>Title</th>
            <th>Genre</th>
            <th>Year Of Released</th>
            <th>Price</th>
            <th>Publised Date</th>
            <th>Author Id</th>
            <th>Actions</th>
        </tr>
        @foreach(var b in Model)
        {
            <tr class="table-default">
                <td>@b.Id</td>
                <td>@b.Title</td>
                <td>@b.Genre</td>
                <td>@b.Year</td>
                <td>@b.Price.ToString("C")</td>
                <td>@b.Publiser</td>
                <td>@b.AuthorID</td>
                <td>
                    <form asp-action="Delete" asp-controller="Books" asp-route-id="@b.Id" method="post">
                        <a class="btn btn-sm btn-info" asp-action="Edit" asp-route-id="@b.Id">Edit</a> 
                        <a asp-action="Index" asp-controller="Reviews" asp-route-id="@b.Id" class="btn btn-sm btn-primary">Reviews</a>
                       <input type="hidden" name="Id" value="@b.Id" />
                        <button type="submit" class="btn btn-sm btn-danger">Delete</button>
                    </form>
                </td>
            </tr>

        }
    </table>
</div>